# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: 1.8.1
_src_path: gh:algorandfoundation/algokit-python-template
author_email: manasmk05@gmail.com
author_name: MaxVon89
contract_name: hello_world
deployment_language: python
preset_name: starter
project_name: MMK_Algorand

